services:
  app:
    build: .
    container_name: fastapi_task_limiter
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  tests:
    build: .
    container_name: fastapi_tests
    volumes:
      - .:/app
    command: poetry run pytest
    depends_on:
      - app